---
title: "Visualização LOAC"
output:
  html_document:
    df_print: paged
  pdf_document: default
  html_notebook: default
---
Esta é uma segunda versão após revisão de Emilly. 

```{r, include = FALSE }
library(tidyverse)
historico <- read_csv("https://github.com/elasComputacao/raio-x-dados/blob/main/data/dados-brutos/historico_alunos_raiox.csv?raw=true")

```
<h2>Separação da disciplina LOAC</h2>
```{r, include=TRUE}
loac <- historico %>%
  filter(stringr::str_detect(nome_disciplina,"LAB.DE ORG.E ARQUITETURA DE COMPUTADORES"))
```
<h3>contagem aprovados e reprovados</h3>
```{r,include=TRUE}
#contagem aprovados e reprovados
aprovacoes<- loac %>%
  filter(stringr::str_detect(situacao,"Apr"))%>%
  summarize(aprovacoes = n_distinct(id))

#considera reprovacao mesmo que passe depois
reprovacoes <- loac %>% 
  filter(situacao == "Reprovado por Falta" | situacao == "Trancado" 
         | situacao == "Reprovado")%>%
  summarize(reprovacoes = n_distinct(id))


#considera apenas quem reprovou e nao graduou
rep_e_nao_graduou <- loac %>% 
  filter((situacao == "Reprovado por Falta" | situacao == "Trancado" | 
            situacao == "Reprovado") & forma_evasao != "GRADUADO")%>%
  summarize(reprovados = n_distinct(id))
```
<h3> Construção de um novo data frame com quantidade de aprovados e reprovados </h3>
```{r,include=TRUE,echo=TRUE}
rep_apv <- data.frame (
  aprovacoes,
  reprovacoes
)
rep_apv$rep_sem_gradu <- rep_e_nao_graduou$reprovados
rep_apv$total <- c(rep_apv$aprovacoes + rep_apv$rep_sem_gradu)
rep_apv$pct_reprovados <- c(((100*rep_apv$rep_sem_gradu)/rep_apv$total))
rep_apv$pct_aprovados <- c(((100*rep_apv$aprovacoes)/rep_apv$total))
rep_apv$pct_reprovacao <- c(((100*rep_apv$reprovacoes)/rep_apv$total))
rep_apv
```
<h2> Sepração de alunos que evadiram do curso </h2>
```{r,include=TRUE}
data_evadido <- loac %>%
  filter(stringr::str_detect(forma_evasao,"CANCE") |
           stringr::str_detect(forma_evasao,"TRANSFERIDO PARA OUTRA IES"))

```

<h3>Plotagem do grafico formas de evasão</h3>
<h4>Frame com formas de evasão e quantidade de ocorrencias</h4>
```{r,include=TRUE,echo=TRUE}
plot_evadidos <- data_evadido %>%
  group_by(forma_evasao)%>%
  summarise(qtd = n_distinct(id))%>%
  arrange(desc(qtd))
plot_evadidos
````
<h4>Visualização em grafico de barras </h4>
```{r,include=TRUE,echo=TRUE}
ggplot(plot_evadidos, aes(y = qtd, x = forma_evasao,fill = forma_evasao)) +
  geom_bar(stat = "identity")+
  xlab("Forma de Evasão") + 
  ylab("quantidade evadidos")+
  theme_light()
````

